[package]
name = "raven-source-alloy"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
alloy.workspace = true
dotenvy = "0.15.7"
futures-util.workspace = true
raven-core = { path = "../raven-core" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
alloy-primitives.workspace = true
eyre.workspace = true
async-trait.workspace = true
raven-plugin-erc20-transfer = { path = "../plugins/erc20-transfer" }
raven-plugin-sdk = { path = "../raven-plugin-sdk" }
raven-runtime = { path = "../raven-runtime" }
tracing-subscriber.workspace = true
