[package]
name = "raven-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
raven-core = { path = "../raven-core" }
raven-plugin-sdk = { path = "../raven-plugin-sdk" }
thiserror.workspace = true

[dev-dependencies]
async-trait.workspace = true
tokio.workspace = true