[package]
name = "raven"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "raven"
path = "src/main.rs"

[dependencies]
alloy-primitives.workspace = true
async-trait.workspace = true
eyre.workspace = true
clap.workspace = true
colored.workspace = true
raven-core = { path = "../raven-core" }
raven-plugin-erc20-transfer = { path = "../plugins/erc20-transfer" }
raven-plugin-sdk = { path = "../raven-plugin-sdk" }
raven-runtime = { path = "../raven-runtime" }
raven-source-alloy = { path = "../raven-source-alloy" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
